name: 'Display greeting message'
on: [push]
jobs:
  Job-Message-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to github runner and my OS is ${{runner.os}}"
      - run: echo "Event name is ${{github.event_name}}"
      - run: ls ~
      - run: pwd
      - run: ls ${{github.workspace}} 
  Job-Build-OnMacMachine:
    runs-on: macos-latest
    steps:
      - name: Clone Current Repository
        uses: actions/checkout@v3
      - name: Install Github CLI
        run: |
          brew update     
          brew install gh
      - name: Install Microsoft Edge Browser
        run: |
          brew update
          brew install --cask microsoft-edge
  Job-Ubuntu-SSH:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v3
    - name: Setup SSH Session
      uses: mxschmitt/action-tmate@v3